### ISSUE TITLE
Missing bytes and statement in ASMC in list file

### ISSUE THREAD

**Issue by wiesl** [nidud/asmc#1]
Missing bytes and statement in ASMC:
00000000                        INIT:		; DISPLAY MSG
00000003  8ED8                  	MOV	DS, AX

Correct with JWASM/UASM:
00000000  B80000                INIT:	MOV	AX, SDATA		; DISPLAY MSG
00000003  8ED8                  	MOV	DS, AX

**Comment by nidud** [comment]
There's a divination between Asmc and Masm/Jwasm in this case where label:opcode is always broken in Asmc. This has to do with parsing of HLL and prevent expansion of code above labels.

Example:

```
foo	macro	reg
	bswap	reg
	exitm	<reg>
	endm

do:	mov	eax,foo( eax )
	...
	mov	ecx,"3210"
	jmp	do
```

As a result the code produced by the macro will be expanded above the label and thus the jump will fail.

```
	bswap	ecx
do:	mov	eax,ecx
	...
```

I provided a fix for the issue but the line will still be broken in the list file.
