### ISSUE TITLE
Linux binaries

### ISSUE THREAD

**Issue by mp81ss** [nidud/asmc#10]
I noticed that you are not shipping linux binaries anymore.
I tried make on linux but give me errors.
Is there a way to have linux binaries?

**Comment by awarm057** [comment]
POLICIA POLICIA

**Comment by nidud** [comment]
The new (untested) version is here:
https://github.com/nidud/asmc/tree/master/source/asmc/linux

The previous version is here:
https://github.com/nidud/asmc/tree/0d32752205547ec3f5c995e6005f282ea7d400bf

**Comment by mp81ss** [comment]
Great, thank you!
