### ISSUE TITLE
error A2004: symbol type conflict : PROPSHEETHEADER

### ISSUE THREAD

**Issue by Greenhorn70** [nidud/asmc#12]
Hi nidud,

I get errors with declaring PROPSHEETHEADER and PROPSHEETPAGE.

```
ShowProperties proc hwndParent:HWND

local hInstance:HINSTANCE
local psh:PROPSHEETHEADER
local psp[3]:PROPSHEETPAGE
```

1>PeaOptions.asm(485): error A2004: symbol type conflict : PROPSHEETHEADER
1>PeaOptions.asm(486): error A2004: symbol type conflict : PROPSHEETPAGE

Defined in https://github.com/nidud/asmc/blob/master/include/prsht.inc

Kind Regards
Greenhorn

**Comment by nidud** [comment]
Added a new translation from the Win81SDK. There's some strange version-definitions there so `psh` default to `PROPSHEETHEADERA_V2` and `psp` to `PROPSHEETPAGEA_V4.`

However, this seems match the current version of [PROPSHEETHEADER](https://learn.microsoft.com/en-us/windows/win32/controls/pss-propsheetheader) and [PROPSHEETPAGE](https://learn.microsoft.com/en-us/windows/win32/controls/pss-propsheetpage).

**Comment by Greenhorn70** [comment]
Fine, works now.
