### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by Tachi107** [nidud/asmc#14]
Hi! Could you consider tagging releases? It would be really helpful for downstream packagers. Thanks :)

**Comment by nidud** [comment]
Some high confidence in my git-skills there ;-)

As of now things are a bit unstable as there are frequent changes made so there's currently no releases. This mostly related to HLL constructs and other experimental things that haven't settled yet.

**Comment by Tachi107** [comment]
> Some high confidence in my git-skills there ;-)

To be honest I never tagged anything with git either, I only used GitHub's UI :/

> As of now things are a bit unstable as there are frequent changes made so there's currently no releases. This mostly related to HLL constructs and other experimental things that haven't settled yet.

Alright, I'll wait. Thanks :)
