### ISSUE TITLE
asmc64 is a 32 bit binary

### ISSUE THREAD

**Issue by darealshinji** [nidud/asmc#15]
I check asmc64 with the file command:
```
~/Downloads/asmc/source/asmc$ file ../../bin/asmc64
../../bin/asmc64: ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, not stripped
```

Same as asmc:
```
:~/Downloads/asmc/source/asmc$ file ../../bin/asmc
../../bin/asmc: ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, not stripped
```

In fact it actually refuses to assemble with the `-elf64` flag.

**Comment by nidud** [comment]
Similar to the [exe tool](../tree/master/source/tools/exe).
```
\VC19\bin\Hostx86\x64\ml64.exe:
 Machine:       I386
 ImageBase:     00400000

\VC19\bin\Hostx64\x64\ml64.exe:
 Machine:       AMD64
 ImageBase:     0000000140000000
```
There are 32 and 64-bit versions of ML64, same with ML, so the 64 thing is not the bitness of the binary. The difference has more to do with target CPU. ML/ASMC defaults to 8086 and ML64/ASMC64 only target x64. 

ASMC64.EXE default to COFF/FASTCALL so the `-win64` flag has no use there. `-elf64` may be used for ELF64/SYSCALL but `-elf` is not supported. 

ASMC64 default to  ELF64/SYSCALL so the `-elf64` flag has no use there but should work (silently ignored).

**Comment by teoberi** [comment]
`file uasm`

> uasm: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, stripped

**Comment by darealshinji** [comment]
I see. The name `asmc64` and the `X64` make flag were confusing me, as they implied to me I was generating an x86-64 executable.

**Comment by nidud** [comment]
asmc64 is now 64-bit

`file asmc64`

> asmc64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=0ed1064c342b4e8b9d6b38304d089cebe812fd62, stripped
