### ISSUE TITLE
Assembled asmc binary cannot rebuild itself

### ISSUE THREAD

**Issue by darealshinji** [nidud/asmc#16]
I can build asmc on Linux with `make -f GccLinux.mak` and it's all fine. But when I try to do it again with the just gerenated asmc binary it fails:
```
$ ./asmc -nologo -nolib -Zp4 -elf -Cs -Isrc/inc -I../../include -Fo src/asmerr.o src/asmerr.asm
 Assembling: src/asmerr.asm
ASMC : fatal error A1901: Internal Assembler Error
```

**Comment by teoberi** [comment]
I can confirm that too.

> gcc -m32 -o asmc src/asmc.o src/asmerr.o src/assemble.o src/assert.o src/assume.o src/backptch.o src/bin.o src/branch.o src/class.o src/cmdline.o src/codegen.o src/coff.o src/com.o src/condasm.o src/context.o src/cpumodel.o src/data.o src/dbgcv.o src/directiv.o src/elf.o src/end.o src/enum.o src/equate.o src/expans.o src/expreval.o src/extern.o src/fastcall.o src/fastpass.o src/fixup.o src/for.o src/fpfixup.o src/hll.o src/Indirection.o src/input.o src/invoke.o src/label.o src/linnum.o src/listing.o src/logo.o src/loop.o src/lqueue.o src/ltype.o src/macro.o src/mangle.o src/mem2mem.o src/memalloc.o src/namespace.o src/new.o src/omf.o src/omffixup.o src/omfint.o src/operator.o src/option.o src/parser.o src/posndir.o src/pragma.o src/preproc.o src/proc.o src/qfloat.o src/reswords.o src/return.o src/safeseh.o src/segment.o src/simsegm.o src/string.o src/switch.o src/symbols.o src/tokenize.o src/typeid.o src/types.o src/undef.o
> /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib32/Scrt1.o: in function `_start':
> (.text+0x2c): undefined reference to `main'
> collect2: error: ld returned 1 exit status
> make: *** [GccLinux.mak:92: asmc] Error 1

**Comment by darealshinji** [comment]
The undefined reference to main comes from the not fully generated object files (they might even be all 0 bytes). That issue is related to https://github.com/nidud/asmc/issues/17 (make doesn't fail and tries to link the unfinished .o files).

**Comment by nidud** [comment]
I went another round and fixed the internal error but there's still an issue, which is somewhat random but specific.
```
src/elf.asm(1442) : error A2006: undefined symbol : get_n_reloc_s_sections
...
```
Original label / error label
```
print_source_nesting_structure
printource_nenesting_structure

get_num_reloc_sections
get_n_reloc_s_sections

omf_write_debug_tables
omf_wrt_debugug_tables

SymMakeAllSymbolsPublic
SymMaAllSymbobolsPublic
```
It's difficult to say where this comes from as it cant be reproduced in the OW-Linux or Windows versions.

**Comment by nidud** [comment]
The bug appear to be in the string routines in the GCC library as it fails to handle regular byte copy. This is fixed in v2.33.24 as far as building Asmc but there may be other instances where this becomes a problem. The culprit:
```assembly
strcpy(esi, "call")
strcat(esi, &[esi+6])
```
This flipp INVOKE to CALL if no arguments is used. Test case:
```assembly
ifndef _WIN64
    .486
    .model flat, syscall
    rax equ <eax>
    rdx equ <edx>
endif

printf proto :ptr, :vararg
strcpy proto :ptr, :ptr
strcat proto :ptr, :ptr

.code

main proc

    lea rdx,[strcpy("invoke print_source_nesting_structure", "call")+6]
    printf("%s\n", strcat(rax, rdx))
   .return 0

main endp

    end
```
build:
```assembly
asmc -elf test.asm
gcc -m32 -o test test.o
...
asmc64 test.asm
gcc -o test test.o
```
It fails in 32-bit but the 64-bit version works.

**Comment by darealshinji** [comment]
I can bootstrap it, but it doesn't assemble the 7zip asm files:
```
asmc -elf64 -DABI_LINUX -Fo_o/ ../../../../Asm/x86/AesOpt.asm
asmc64 -DABI_LINUX -Fo_o/ ../../../../Asm/x86/AesOpt.asm
```
Both commands fail. It also fails with your pre-build versions.

**Comment by nidud** [comment]
It works fine on my end, with both versions. However, the changes to 7zAmc.asm needs to be added:
```assembly
ifdef @wordsize
if @wordsize eq 8
  x64 equ 1
endif
else
 x64 equ 1
endif
```

**Comment by teoberi** [comment]
And:
`sed -i 's|ifdef ymm0|ifdef x64|g' Asm/x86/AesOpt.asm`
`sed -i 's|LFLAGS_ALL = -s $(MY_ARCH_2) $(LDFLAGS) $(LD_arch) $(OBJS) $(MY_LIBS) $(LIB2)|LFLAGS_ALL = -s $(MY_ARCH_2) $(LDFLAGS) -Wl,-z,noexecstack $(LD_arch) $(OBJS) $(MY_LIBS) $(LIB2)|g' CPP/7zip/7zip_gcc.mak`

**Comment by darealshinji** [comment]
Great, it works now, thanks.
