### ISSUE TITLE
asmc returns 0 on error

### ISSUE THREAD

**Issue by darealshinji** [nidud/asmc#17]
When asmc reports an error it exits with 0 instead of 1 (or non-zero):
```
 Assembling: src/asmerr.asm
ASMC : fatal error A1901: Internal Assembler Error
$ echo $?
0
```

But it should return non-zero so that compilation stops when the first error appears.

**Comment by nidud** [comment]
The error 1901 is more of an internal debug feature than a real error so it shouldn't occur under normal circumstances. In this case the underlying error was related to the exit process itself which should now be fixed.

```
$ asmc src/asmerr.asm
Asmc Macro Assembler Version 2.33.24
Copyright (C) The Asmc Contributors. All Rights Reserved.

 Assembling: src/asmerr.asm
src/asmerr.asm(7) : fatal error A1000: cannot open file : io.inc
$ echo $?
1

```
