### ISSUE TITLE
Help compiling Asmc v2.33.27

### ISSUE THREAD

**Issue by teoberi** [nidud/asmc#18]
**Ubuntu 20.04.3 LTS with gcc-multilib**
`make -f GccLinux.mak`
`make -f GccLinux.mak ASMC64=1`
Compiling using **GccLinux.mak** is OK as well as running executables generated **asmc/asmc64**
`make -f GccLinux64.mak`
`make -f GccLinux64.mak  X64=1`
Compiling using GccLinux64.mak fails at the linking step.

> /usr/bin/ld: x64/asmc.o: relocation R_X86_64_PC32 against symbol `exit@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: final link failed: bad value
> collect2: error: ld returned 1 exit status
> make: *** [GccLinux64.mak:92: asmc64] Error 1

**Slackware64-current  (pure 64-bit)**
`make -f GccLinux64.mak`
`make -f GccLinux64.mak  X64=1`
Compiling using **GccLinux64.mak** runs without any errors but when running the generated executables I get in both cases the message:

> Segmentation fault (core dumped)

Another problem, there is a message in the syslog:
xxx kernel: process 'tmp/asmc/bin/asmc' started with executable stack
The problem also appears in the case of 7-Zip, here a solution exists in the pkgbuild for [OpenSUSE](https://build.opensuse.org/package/view_file/home:post-factum/7-zip/PKGBUILD?expand=1),  line 16 (**-Wl,-z,noexecstack**).
Some information [here](https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart#If_all_else_fails).
I don't know if this is also the case for asmc?

Other questions?
As of version 2.33.25, the asmc64 file is missing from the bin folder. Is asmc file (from bin folder) generated with OWLinux.mak or GccLinux.mak?

**Comment by nidud** [comment]
Note that the 64-bit version is experimental at the moment so it serves more like a playground for testing the CodeView 8 debug implementation for use in newer versions of Visual Studio (2019/2022). The source is however written for Linux as well (also experimental) but this needs further testing.

> Another problem, there is a message in the syslog:
> xxx kernel: process 'tmp/asmc/bin/asmc' started with executable stack
> The problem also appears in the case of 7-Zip, here a solution exists in the pkgbuild for OpenSUSE, line 16 (-Wl,-z,noexecstack).
> Some information here.
> I don't know if this is also the case for asmc?
> 

Asmc extensively use stack allocation internally and the Windows version reserves around 2M of stack for this purpose. For the 32-bit version this is not that important as it commit the stack dynamically as needed but for the 64-bit version this should be set by the linker.

So insted of a _noexecstack_ there should be a [_moreexecstack_](../blob/master/source/asmc/asmc.vcxproj#L43) option.

**Comment by nidud** [comment]
I added stacksize to the command line to gcc:

`gcc -o $@ -z --execstack -z --stacksize=0x20000 $^`

The binary built (asmc64) is now added to the bin directory.

**Comment by teoberi** [comment]
Thanks. I will wait for the development of the 64-bit version (for compilation in Slackware64-current).
