### ISSUE TITLE
What happened to Bootstrapping without a copy of asmc?

### ISSUE THREAD

**Issue by teoberi** [nidud/asmc#18]
https://github.com/nidud/asmc/issues/15#issuecomment-2424149447
Have asmc and asmc64 reappeared, any problems?

**Comment by nidud** [comment]
It needs to be possible to build a 32-bit version which cant be done without a binary or a second _purification ritual_ for this purpose. The conversion is also problematic as it is not fully automated and rely on a modified version of objconv.

So yes, there are a few problems.
