### ISSUE TITLE
When outputting help messages, use '-' instead of '/' on Linux

### ISSUE THREAD

**Issue by ghost** [nidud/asmc#19]
If I run `asmc` ([from here](https://github.com/nidud/asmc/blob/master/bin/asmc)), I see the message `Use option /? for more info`.

However, if I follow the message and run `asmc /?`, it will not work:
```
 Assembling: /?
ASMC : fatal error A1000: cannot open file : /?
```

I need to change `/?` to `-?`:
```
        ASMC [ /options ] filelist

/<0|1|..|10>[p] Set CPU: 0=8086 (default), 1=80186, 2=80286, 3=80386, 4=80486,
 5=Pentium,6=PPro,7=P2,8=P3,9=P4,10=x86-64; <p> allows privileged instructions
/assert Generate .assert() code            /r Recurse subdirectories
(...)
```

The help messages are using `/`, which will not work.
Therefore I think it would be better to change them to `-`, e.g.:
`Use option -? for more info`
```
-assert Generate .assert() code            -r Recurse subdirectories
```

**Comment by nidud** [comment]
Yes, in Linux /this will be a path.

Asmc is however a Masm compatible assembler and thus use the standard documentation for Windows applications.

[ML and ML64 command-line reference](https://docs.microsoft.com/en-us/cpp/assembler/masm/ml-and-ml64-command-line-reference?view=msvc-170)

[Asmc Command-Line Reference](https://github.com/nidud/asmc/blob/master/doc/command/readme.md)

That aside it should probably change the logo and help output for the Linux version so I will look into that.
