### ISSUE TITLE
Cannot build asmc64 on 64-bit Linux

### ISSUE THREAD

**Issue by anta40** [nidud/asmc#20]
I have a VPS running Debian 64, with 32-bit compatibility libs installed.

Running `make -f GccLinux64.mak`, I got this:

> ..
> /usr/bin/ld: x64/symbols.o: warning: relocation against `localtime@@GLIBC_2.2.5' in read-only section `.text'
> /usr/bin/ld: x64/asmc.o: relocation R_X86_64_PC32 against symbol `signal@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: final link failed: bad value
> collect2: error: ld returned 1 exit status
> make: *** [GccLinux64.mak:92: asmc] Error 1

Modifying GccLinux64.mak like this:

> $(BIN): $(OBJS)
>         gcc -o $@ $^ -fPIE 

Doesn't solve the problem. Still the same linker error. On the other side, `make -f GccLinux.mak` works fine.
I'm using gcc 11.2.0, BTW.

**Comment by teoberi** [comment]
https://github.com/nidud/asmc/issues/18#issue-1096113497
