### ISSUE TITLE
Proto for Get-/SetLayout missing in WinGDI.inc

### ISSUE THREAD

**Issue by Greenhorn70** [nidud/asmc#29]
Hi nidud,

I'm missing the protos for GetLayout and SetLayout in WinGDI.inc.

```Assembly
if (WINVER GE 0x0500)
SetLayout proto WINAPI :HDC, :DWORD
GetLayout proto WINAPI :HDC
endif
```

Kind Regards
Greenhorn

**Comment by nidud** [comment]
I've added the [h2inc](https://github.com/nidud/asmc/tree/master/source/tools/h2inc) tool and used that to translate a new version of wingdi. There's no "cheating" there so `LOGFONTA` is a typedef and the type is `tagLOGFONTA`.
