### ISSUE TITLE
New .dot syntax breaks existing code since V2.30

### ISSUE THREAD

**Issue by wiesl** [nidud/asmc#3]
Hello,

According to the history https://github.com/nidud/asmc/blob/master/source/asmc/history.txt in version 2.30 a lot of keywords were renamed with the .dot syntax. This breaks existing valid ASM code and a lot of code would have to be changed of existing projects. Can you please add backward compatibility for the old keywords without dots or add a switch.
- renamed .SWITCH NOTEST to .SWITCH JMP
- renamed .CLASSDEF to .CLASS
- renamed C to CCALL
- renamed TYPE to TYPEOF
- renamed SIZE, LENGTH, HIGH, LOW, THIS, and WIDTH to dot names
- renamed directive NAME, TITLE, PAGE, SUBTITLE, and SUBTTL to dot names

Some examples:
#error A2206: missing operator in expression
	cmp	bx, length inbuf 
#error A2008: syntax error : TITLE
	TITLE	MYTITLE
#error A2008: syntax error : page	
	page	64, 131

BTW: Is this already planned with oldkeyw.h?

Thnx.

**Comment by nidud** [comment]
Yes, and a back-compatible switch for old keywords is added.

[Disable non Masm keywords](https://github.com/nidud/asmc/blob/master/doc/command/Znk.md
)

As for NOTEST and .CLASSDEF they are obsolete. C may still be used as a calling convention (as before) but also as an identifier.

**Comment by wiesl** [comment]
Thnx, works.
