### ISSUE TITLE
asmc crashes with switch /Zi(8)3

### ISSUE THREAD

**Issue by Greenhorn70** [nidud/asmc#34]
If I assemble my source with switch /zi3 or Zi83, asmc crashes.

`
asmc64.exe /nologo /frame /Cs /Sg /Zi3 /ws /Fo"x64\Debug\CoolCtrl.obj" /D"COOLCTRL_DLL" /Fl"x64\Debug\CoolCtrl.lst" /I"D:\asmc\include" /Cp /W2 /Zp8 CoolCtrl.asm
 Assembling: CoolCtrl.asm
EXCEPTION: Segment violation

This message is created due to unrecoverable error
and may contain data necessary to locate it.

Code:   C0000005
Flags:  00000000

        RAX: 0000000000000005 R8:  0000000000000015
        RBX: 000000000032FB68 R9:  000000000032FC40
        RCX: 0000000000008001 R10: 0000000000000001
        RDX: 0000000000C2009E R11: 00000000000011E4
        RSI: 00000000012D5AC0 R12: 0000000000000000
        RDI: 0000000000C20096 R13: 0000000000000000
        RBP: 000000000032FAC8 R14: 0000000000000000
        RSP: 000000000032FA40 R15: 0000000000458D80
        RIP: 00000000004155EF 8BFC458BFE418966
             044F896600000013 8966FF08548D104E

        EFL: 0000001010000111
             r n oditsz a p c
`
The other Zi switches are working well, so I guess it's due to constants in debug information.
Listing file is created fine, object file is created but 0 bytes in size.

EDIT:
This is at least since version 2.34.01

**Comment by nidud** [comment]
```assembly
    RIP: 00000000004155EF 8BFC458BFE418966
         044F896600000013 8966FF08548D104E
```
asmc64 -bin test.asm
```assembly
.code
dq 0x044F896600000013 ; [rip-8]
dq 0x8BFC458BFE418966 ; [rip]
dq 0x8966FF08548D104E ; [rip+8]
end
```
objdump -M intel -b binary -D -m i386:x86-64 test.bin
```assembly
   4:	66 89 4f 04          	mov    WORD PTR [rdi+0x4],cx
   8:	66 89 41 fe          	mov    WORD PTR [rcx-0x2],ax ; <-- exception
   c:	8b 45 fc             	mov    eax,DWORD PTR [rbp-0x4]
   f:	8b 4e 10             	mov    ecx,DWORD PTR [rsi+0x10]
  12:	8d 54 08 ff          	lea    edx,[rax+rcx*1-0x1]
```
[dbgcv.asm(1141)](https://github.com/nidud/asmc/blob/master/source/asmc/src/dbgcv.asm#L1141)
```assembly
if EQUATESYMS
...
            lea rdx,[rdi].CONSTSYM.name
        .endif
...
            mov [rdi].CONSTSYM_16t.typind,cx
        .endif

        mov [rcx-2],ax ; <-- exception
        mov eax,len
        mov ecx,[rsi].asym.name_size
        lea edx,[rax+rcx-2+1]
```
I guess RDX should be used there...

**Comment by Greenhorn70** [comment]
Assembles fine now :)
