### ISSUE TITLE
Get wrong size for NONCLIENTMETRICS(W)

### ISSUE THREAD

**Issue by Greenhorn70** [nidud/asmc#35]
I get the wrong size for [NONCLIENTMETRICSW](https://github.com/nidud/asmc/blob/96d2803040babcb47c8873b275f1b971675b3e4e/include/winuser.inc#L9063) from winuser.inc.
I get 520 bytes but it should be 504 bytes.
My guess is that it is from [LOGFONTW](https://github.com/nidud/asmc/blob/96d2803040babcb47c8873b275f1b971675b3e4e/include/wingdi.inc#L1452) in wingdi.inc but I can't find an error in it.
Debug iinfo shows for NONCLIENTMETRICS only members from cbSize to iCaptionHeight.

![20-07-_2022_03-35-01](https://user-images.githubusercontent.com/106280507/179876728-184eba58-99f8-40dd-90fd-edadb348f759.png)
Best Regards
Greenhorn

**Comment by nidud** [comment]
The size of LOGFONTW is correct but the alignment is messed up if the struct is a typedef. After the upgrade of the headers LOGFONTW became a typedef of tagLOGFONTW.

Normally the max member size is used for alignment but here the struct size was used. This is a regression from JWASM 2.0.

I added a fix for the alignment but I haven't looked into the debug issue.

**Comment by Greenhorn70** [comment]
I remember that I had this issue with messed debug info a few years ago and IIRC the reason was also because of `typedef tagSOMESTRUCT   SOMESTRUCT`.
That means, if you put a "typedefed" structure like `LOGFONT` as a member of another struct then the debug info is messed up.
But if you would define `LOGFONT` in the "classical" way and put it as a member of another structure debug info is OK.
IIRC, of course ...

**Comment by nidud** [comment]
Here's the same breakpoint in Visual Studio 2022 using -Zi8 so it seems to work there. The "hack" use the actual type here (tagLOGFONTW) but maybe that wont work with older versions of VS or -Zi if that's the case on your end.

![vs2022](https://user-images.githubusercontent.com/19373832/180054726-82e5daee-bc06-4806-8386-1d2182ed4a7e.jpg)

> However, since the main issue is solved, this issue could be closed.
>
> If you like to, we can work on this issue in the Discission forum ?
> Or should I keep this issue open ? Or create a new issue ?

Well, we dived into it so we may as well continue.

**Comment by Greenhorn70** [comment]
> Well, we dived into it so we may as well continue.

OK then. :o)

I had to fall back from VS 2017 Community to VS 2010 Express because my Ms account is deactivated and since I'm not able to receive a SMS (I don't own a mobile), I'm not able to proceed the new invented 2FA.

So, I tested Zi2, Zi3, Zi8, Zi83 with no change.
But while looking at your screenshot ..., it affects more the "Quick View" as shown in my screenshot from my last comment.
The "Locals" window displays it better but also with a little glitch. 

![20-07-_2022_21-04-00](https://user-images.githubusercontent.com/106280507/180062587-a4065e3f-a8b1-409f-9414-0f3e4210a792.png)

Strange, isn't it ?

While debugging, I usually just have the "Registers" window active and look at the variable, constants, etc. with the mouse hovering over it which opens the tooltip-like popup.
If it's too much afford to investigate it, I can live with the current state. But if you're masochistic enough we can go on to make it perfect. :laughing: 
I don't know if VS 2010 is still often used, so you may decide if it is worth to support it.
There are also a few more little glitches as we discussed in the MASM forums.

**Comment by nidud** [comment]
> I had to fall back from VS 2017 Community to VS 2010 Express because my Ms account is deactivated and since I'm not able to receive a SMS (I don't own a mobile), I'm not able to proceed the new invented 2FA.

The last one I used was a NOKIA 3210 but I never actually had a mobile phone in my name.

> There are also a few more little glitches as we discussed in the MASM forums.

I think we improve some things and figured out some of the limitations there as I remember. Applying any major changes may have an effect on older versions here, so if it still works it maybe best to leave it there for now.

**Comment by Greenhorn70** [comment]
> The last one I used was a NOKIA 3210 but I never actually had a mobile phone in my name.

That was exactly my last mobile I owned until I lost it in a pub in 2005. And since nobody ever was calling me on this phone I decided not to get a new one. So I allowed myself the luxury to be unavailable when I'm not at home. :+1: 

> I think we improve some things and figured out some of the limitations there as I remember. Applying any major changes may have an effect on older versions here, so if it still works it maybe best to leave it there for now.

Yes, maybe you're right.
Thanks a lot for your patience and afford, nidud !
