### ISSUE TITLE
Support for elf32 shared libraries syntax

### ISSUE THREAD

**Issue by mp81ss** [nidud/asmc#6]
In nasm, I can do something like this:

```
%macro get_GOT 0 
          call %%getgot 
%%getgot: pop ebx 
          add ebx,_GLOBAL_OFFSET_TABLE_+$$-%%getgot wrt ..gotpc 
%endmacro
```

I don't see any way to replicate it in asmc.
Is it possible?

**Comment by nidud** [comment]
PLT/GOT seems to be mandatory in newer versions of Linux but I haven't really tested or implement any of this in Asmc.

I was thinking this would go away for some reason assuming some external tools or a linker update to convert old libraries was needed or at least possible so I haven't really been in a hurry to implement this.

**Comment by mp81ss** [comment]
You're right, this is 32-bit elf only

**Comment by mp81ss** [comment]
Old arch

**Comment by awarm057** [comment]
HKRZ %%&*^((&%$# GET?l":?)"lgf bSTED!!!!! LOL NO FUNDS FOR YOU LOSERS

**Comment by awarm057** [comment]
CYBER HACKERS NEED TO LEARN HOW TO WORK WITH THEIR HANDS LIKE REAL MEN.
