### ISSUE TITLE
Linux -? not working

### ISSUE THREAD

**Issue by piglu** [nidud/asmc#7]
Hi

`asmc -?` does not work under linux (no matches found: -?) but `asmc -h` (Manjaro linux zsh) idk for win

And thank you for this...seems that GTK apps are much easier to write now :)

**Comment by nidud** [comment]
> `asmc -?` does not work under linux (no matches found: -?) but `asmc -h` (Manjaro linux zsh)

I think it's a wildcard issue. The current version is dynamically linked:
```
$ file ./asmc
./asmc: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=dff01cfef9bf561804e9d7a239bcdd21cd97b38b, for GNU/Linux 3.2.0, stripped
```
So the startup module auto-expands wildcard (* and ?) in the command line and this apparently works differently depending on the build version. In Ubuntu this works fine as long as there are no match for ? (the argument is just passed along) but that don't seem to be the case here.

The assembler handle wildcard internally so this may be an issue:
```
libasmc.a:
	asmc64 -fpic -Zp8 -D_CRTBLD -Cs -r *.asm
```
The gamble here is that there are no `.asm` files in the current directory and the argument will be passed along, but in your case this will end with an error.

A possible fix may be "quotes" for these arguments so maybe you could test if this works:
```
$ asmc "-?"
```

**Comment by nidud** [comment]
I installed Manjaro and it uses a newer version but the makefiles works without any changes. The only thing missing from the default install was `make`.

Well, the `-?` option should be removed and the standard `--help` option added to the Linux version.
