### ISSUE TITLE
Issue with ALIAS

### ISSUE THREAD

**Issue by Erol-2022** [nidud/asmc#8]
Hi Nidud,

Poasm v12 can assemble the code below without any issues :

```
.386
.model flat,stdcall
option casemap:none

OutputText PROTO C :DWORD,:VARARG

ALIAS <OutputText>=<printf>

END
```

printf is exported by msvcrt.lib  The purpose is to map the new symbol OutputText to the printf function.

Trying to assemble with asmc : 

```
asmc.exe /coff Alias.asm

Asmc Macro Assembler Version 2.34.50
Copyright (C) The Asmc Contributors. All Rights Reserved.

 Assembling: Alias.asm
Alias.asm(7) : error A2005: symbol redefinition : OutputText
```

**Comment by nidud** [comment]
Asmc (and Masm) wont allow a direct redefinition of symbols like this. The syntax is:

    ALIAS <alias> = <actual-name>

It's possible to use the UNDEF directive here thought:

```
.386
.model flat,stdcall
option casemap:none

printf      proto c :ptr, :vararg
OutputText  proto c :ptr, :vararg

undef OutputText
ALIAS <OutputText>=<printf>

.code
OutputText("%s(%d)\n", __FILE__, __LINE__)
end
```

**Comment by Erol-2022** [comment]
Hi Nidud,

Thanks for the explanation. I tested your example code.

**Comment by nidud** [comment]
Haven't thought about using [ALIAS](https://github.com/nidud/asmc/blob/master/source/libc/string/memcpy.asm#L10) like this but it's actually more practical than adding global labels.

```C
memmove::
memcpy proc dst:ptr, src:ptr, size:size_t
```
